branch-defaults:
  default:
    environment: blog
    group_suffix: null
global:
  application_name: blog
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Puma)
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
